// export.service.ts — Generates .docx and .xlsx from agent output

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, ShadingType, BorderStyle, Table, TableRow, TableCell,
  WidthType, convertInchesToTwip,
} from 'docx';
import * as XLSX from 'xlsx';

// ── Helpers ──────────────────────────────────────────────────────

function hexToRgb(hex: string): string {
  const h = hex.replace('#', '');
  return h.toUpperCase();
}

const PRIMARY_HEX = '0B5142';
const LIGHT_HEX   = 'F0F6F0';

// ── Markdown-ish line parser ─────────────────────────────────────

type ParsedLine =
  | { kind: 'h1'; text: string }
  | { kind: 'h2'; text: string }
  | { kind: 'bullet'; text: string }
  | { kind: 'quote'; text: string }
  | { kind: 'p'; text: string }
  | { kind: 'blank' };

function parseLines(text: string): ParsedLine[] {
  return text.split('\n').map((raw) => {
    const line = raw.trimEnd();
    if (!line.trim()) return { kind: 'blank' };
    if (line.startsWith('# '))  return { kind: 'h1',     text: line.slice(2) };
    if (line.startsWith('## ')) return { kind: 'h2',     text: line.slice(3) };
    if (line.startsWith('- ') || line.startsWith('* ')) return { kind: 'bullet', text: line.slice(2) };
    if (line.startsWith('> '))  return { kind: 'quote',  text: line.slice(2) };
    return { kind: 'p', text: line };
  });
}

// ── Word (.docx) export ──────────────────────────────────────────

export async function generateWordDoc(params: {
  title: string;
  agentName: string;
  runId: string;
  generatedAt: string;
  content: string;
}): Promise<Buffer> {
  const lines = parseLines(params.content);
  const paragraphs: Paragraph[] = [];

  // Cover heading
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: params.title,
          bold: true,
          size: 52,
          color: PRIMARY_HEX,
          font: 'Calibri',
        }),
      ],
      spacing: { after: 200 },
    }),
  );

  // Subtitle line
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Merris · ${params.agentName} · ${params.generatedAt} · Run ${params.runId}`,
          size: 18,
          color: '9AA0A6',
          font: 'Courier New',
        }),
      ],
      spacing: { after: 600 },
    }),
  );

  // Divider
  paragraphs.push(
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: PRIMARY_HEX } },
      spacing: { after: 400 },
    }),
  );

  // Body paragraphs
  for (const line of lines) {
    switch (line.kind) {
      case 'h1':
        paragraphs.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: line.text, bold: true, size: 36, color: PRIMARY_HEX, font: 'Calibri' })],
            spacing: { before: 480, after: 160 },
          }),
        );
        break;

      case 'h2':
        paragraphs.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_2,
            children: [new TextRun({ text: line.text, bold: true, size: 26, color: PRIMARY_HEX, font: 'Calibri' })],
            spacing: { before: 320, after: 120 },
          }),
        );
        break;

      case 'bullet':
        paragraphs.push(
          new Paragraph({
            bullet: { level: 0 },
            children: [new TextRun({ text: line.text, size: 22, font: 'Calibri' })],
            spacing: { before: 60, after: 60 },
          }),
        );
        break;

      case 'quote':
        paragraphs.push(
          new Paragraph({
            indent: { left: convertInchesToTwip(0.4) },
            shading: { type: ShadingType.CLEAR, fill: LIGHT_HEX },
            border: { left: { style: BorderStyle.SINGLE, size: 12, color: PRIMARY_HEX } },
            children: [
              new TextRun({ text: line.text, italics: true, size: 22, color: '5F6368', font: 'Calibri' }),
            ],
            spacing: { before: 120, after: 120 },
          }),
        );
        break;

      case 'p':
        paragraphs.push(
          new Paragraph({
            children: [new TextRun({ text: line.text, size: 22, font: 'Calibri' })],
            spacing: { before: 80, after: 80 },
          }),
        );
        break;

      case 'blank':
        paragraphs.push(new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 60, after: 60 } }));
        break;
    }
  }

  // Footer note
  paragraphs.push(
    new Paragraph({
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: 'E8EAE8' } },
      children: [
        new TextRun({
          text: `Merris ESG Intelligence Platform · This document was generated by AI and should be reviewed before publication.`,
          size: 16,
          color: 'C4CAC4',
          font: 'Courier New',
        }),
      ],
      spacing: { before: 600 },
      alignment: AlignmentType.CENTER,
    }),
  );

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: {
            top:    convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left:   convertInchesToTwip(1.25),
            right:  convertInchesToTwip(1.25),
          },
        },
      },
      children: paragraphs,
    }],
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
      },
    },
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

// ── Excel (.xlsx) export ─────────────────────────────────────────

export interface ExcelRow {
  section: string;
  metric: string;
  value: string;
  unit?: string;
  framework?: string;
  status?: string;
}

export function generateExcelWorkbook(params: {
  title: string;
  agentName: string;
  runId: string;
  generatedAt: string;
  content: string;
  rows?: ExcelRow[];
}): Buffer {
  const wb = XLSX.utils.book_new();

  // ── Sheet 1: Summary ─────────────────────────────────────────
  const summaryData: (string | number)[][] = [
    ['Merris ESG Intelligence — Export'],
    [''],
    ['Agent',       params.agentName],
    ['Run ID',      params.runId],
    ['Generated',   params.generatedAt],
    [''],
    ['── AGENT OUTPUT ──────────────────────────────'],
    [''],
  ];

  // Add content lines
  for (const line of params.content.split('\n').slice(0, 200)) {
    summaryData.push([line]);
  }

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

  // Style column widths
  summarySheet['!cols'] = [{ wch: 80 }, { wch: 40 }];

  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');

  // ── Sheet 2: Data Points (if rows provided or extracted from content) ──
  const rows = params.rows ?? extractMetricsFromContent(params.content);

  if (rows.length > 0) {
    const headers = ['Section', 'Metric', 'Value', 'Unit', 'Framework', 'Status'];
    const dataRows = rows.map((r) => [
      r.section, r.metric, r.value, r.unit ?? '', r.framework ?? '', r.status ?? '',
    ]);

    const dataSheet = XLSX.utils.aoa_to_sheet([headers, ...dataRows]);
    dataSheet['!cols'] = [
      { wch: 20 }, { wch: 35 }, { wch: 20 }, { wch: 12 }, { wch: 18 }, { wch: 15 },
    ];

    XLSX.utils.book_append_sheet(wb, dataSheet, 'Data Points');
  }

  // ── Sheet 3: Metadata ──────────────────────────────────────────
  const metaSheet = XLSX.utils.aoa_to_sheet([
    ['Property', 'Value'],
    ['Platform', 'Merris ESG Intelligence'],
    ['Version',  '1.0'],
    ['Title',    params.title],
    ['Agent',    params.agentName],
    ['Run ID',   params.runId],
    ['Generated',params.generatedAt],
    ['Disclaimer','This document was generated by AI. Review before publication.'],
  ]);
  metaSheet['!cols'] = [{ wch: 20 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, metaSheet, 'Metadata');

  return Buffer.from(XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }));
}

// ── Simple metric extractor from agent output text ───────────────

function extractMetricsFromContent(text: string): ExcelRow[] {
  const rows: ExcelRow[] = [];
  const lines = text.split('\n');
  let currentSection = 'General';

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    if (line.startsWith('# ') || line.startsWith('## ')) {
      currentSection = line.replace(/^#+\s*/, '');
      continue;
    }

    // Match patterns like "Scope 1: 45,000 tCO2e" or "GHG Emissions: 120,000 t"
    const metricMatch = line.match(/^[-•*]?\s*([^:]+):\s*([0-9,.\s]+)\s*([a-zA-Z%°/²³]+)?/);
    if (metricMatch) {
      const [, metric, value, unit] = metricMatch;
      if (metric && value && value.trim().length > 0) {
        rows.push({
          section: currentSection,
          metric:  metric.trim(),
          value:   value.replace(/,/g, '').trim(),
          unit:    unit?.trim(),
          status:  'extracted',
        });
      }
    }
  }

  return rows.slice(0, 100);
}
